name: 'Create Artifact Bundle'
authod: 'giginet'
description: 'Create artifact bundle for Swift Package'
inputs:
  artifact_name:
    description: 'Name of the executable to collect'
    required: true
  version:
    description: 'Version of the executable'
    required: false
    default: '${{ github.event.release.tag_name || github.ref_name }}'
  package_path:
    description: 'Path to the Swift package directory'
    required: false
    default: '.'
outputs:
  bundle_path:
    description: 'An absolute path to the created artifact bundle zip file'
  bundle_sha256:
    description: 'A SHA256 hash of the artifact bundle'
  bundle_filename:
    description: 'A filename of the artifact bundle'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'package'
  color: 'orange'