name: 'Create Artifact Bundle'
description: 'Create artifact bundle for Swift executables'
inputs:
  executable-name:
    description: 'Name of the executable to collect'
    required: true
  version:
    description: 'Version of the executable'
    required: true
  package-path:
    description: 'Path to the Swift package directory'
    required: false
    default: '.'
outputs:
  artifact_path:
    description: 'Path to the created artifact bundle zip file'
  sha256:
    description: 'SHA256 hash of the artifact bundle'
runs:
  using: 'node20'
  main: 'dist/index.js'
